name: "Access Request" # The name of issue
description: "Use this issue to request access to my private repositories"
title: "[ACCESS REQUEST]"
labels:
  - access request
body:
  - type: input
    id: github_username
    attributes:
      label: "Your GitHub username"
      description: "I’ll invite you to my private repo once you submit this."
      placeholder: "username"
