name: Invite on Access Request

on:
  issues:
    types: [opened]

jobs:
  invite:
    # only proceed if the new issue’s title starts with “[ACCESS REQUEST]”
    if: startsWith(github.event.issue.title, '[ACCESS REQUEST]')
    runs-on: ubuntu-latest

    steps:
      - name: Extract GitHub username
        id: extract
        run: |
          USERNAME=$(echo "${{ github.event.issue.body }}" \
            | grep -A1 "Your GitHub username" \
            | tail -n1 \
            | xargs)
          echo "username=$USERNAME" >> $GITHUB_OUTPUT

      - name: Invite user to private repo
        uses: peter-evans/invite-collaborator@v2
        with:
          repo: jseihee/senescence-classif
          user: ${{ steps.extract.outputs.username }}
          permission: pull
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Comment confirmation
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ steps.extract.outputs.username }}!  
            You’ve been invited to **jseihee/senescence-classif**.  
            Check your GitHub notifications to accept.
