name: Invite on Access Request

on:
  issues:
    types: [opened]

jobs:
  invite:
    # only run for your template-based issue
    if: startsWith(github.event.issue.title, '[ACCESS REQUEST]')
    runs-on: ubuntu-latest

    steps:
      - name: Extract GitHub username
        id: extract
        run: |
          USERNAME=$(echo "${{ github.event.issue.body }}" \
            | grep -A1 "Your GitHub username" \
            | tail -n1 \
            | xargs)
          echo "username=$USERNAME" >> $GITHUB_OUTPUT

      - name: Invite user to private repo via API
        run: |
          echo "Inviting ${{ steps.extract.outputs.username }} to jseihee/senescence-classif…"
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/jseihee/senescence-classif/collaborators/${{ steps.extract.outputs.username }} \
            -d '{"permission":"pull"}'
        # The "pull" permission gives read‐only access. Change to "push" if you want write.

      - name: Comment confirmation
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ steps.extract.outputs.username }}!  
            I’ve invited you to **jseihee/senescence-classif** (read access).  
            Check your GitHub notifications to accept.
