name: "Invite on Access Request"

permissions:
  issues: write
  contents: read

on:
  issues:
    types:
      - opened
      - labeled

jobs:
  # 1. Acknowledge new requests
  acknowledge:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge request
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks @${{ github.event.issue.user.login }}!  
            Your access request has been received. A maintainer will review it shortly.
      - name: Assign to maintainer
        uses: peter-evans/assign-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          assignees: jseihee

  # 2. Invite once approved
  invite:
    needs: acknowledge
    if: |
      github.event.action == 'labeled' && 
      github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Extract GitHub username
        id: extract
        run: |
          BODY="${{ github.event.issue.body }}"
          USERNAME=$(echo "$BODY" \
            | awk '/./{ line=$0 } END{ print line }' \
            | xargs)
          echo "username=$USERNAME" >> $GITHUB_OUTPUT

      - name: Invite user to private repo via API
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/jseihee/senescence-classif/collaborators/${{ steps.extract.outputs.username }} \
            -d '{"permission":"pull"}'

      - name: Comment confirmation
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ steps.extract.outputs.username }}!  
            Your request has been **approved** and an invite has been sent.  
            Please check your GitHub notifications to accept.
