name: Invite on Access Request

on:
  issues:
    types: [opened]

jobs:
  invite:
    # only run if the issue has the “access request” label
    if: contains(github.event.issue.labels.*.name, 'access request')
    runs-on: ubuntu-latest

    steps:
      - name: Invite user to private repo
        uses: peter-evans/invite-collaborator@v2
        with:
          repo: jseihee/senescence-classif   # ← change this
          user: ${{ github.event.issue.body | fromJsonSafe }}  # or parse out the username field
          permission: pull
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Comment confirmation
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ github.event.issue.body.github_username }}!  
            You’ve been invited to **jseihee/senescence-classifO**.  
            Check your notifications to accept.
