name: Invite on Access Request

# ── Grant the workflow permission to post comments on issues ───────────────
permissions:
  issues: write
  contents: read

on:
  issues:
    types: [opened]

jobs:
  invite:
    # only handle issues created from your template
    if: startsWith(github.event.issue.title, '[ACCESS REQUEST]')
    runs-on: ubuntu-latest

    steps:
      - name: Debug: dump issue body
        run: |
          echo "=== ISSUE BODY BEGIN ==="
          echo "${{ github.event.issue.body }}"
          echo "=== ISSUE BODY END ==="

      - name: Extract GitHub username
        id: extract
        run: |
          # find the line after “Your GitHub username” and trim whitespace
          USERNAME=$(echo "${{ github.event.issue.body }}" \
            | awk '/Your GitHub username/{ getline; print; exit }' \
            | xargs)
          echo "Extracted username: '$USERNAME'"
          echo "username=$USERNAME" >> $GITHUB_OUTPUT

      - name: Invite user to private repo via API
        run: |
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/jseihee/senescence-classif/collaborators/${{ steps.extract.outputs.username }} \
            -d '{"permission":"pull"}'

      - name: Comment confirmation
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hi @${{ steps.extract.outputs.username }}!  
            I’ve invited you to **jseihee/senescence-classif** with read-only access.  
            Please check your GitHub notifications to accept.
